### ISSUE TITLE
Ubuntu 16.04 having this error always

### ISSUE THREAD

**Issue by jared03** [aeonix/aeon-legacy#66]
[ 47%] Linking CXX executable connectivity_tool
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::program_options::variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:167: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
/usr/local/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
/usr/local/include/boost/program_options/errors.hpp:373: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name() const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg[abi:cxx11]'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::program_options::typed_value<unsigned int, char>::name() const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg[abi:cxx11]'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::program_options::typed_value<unsigned long, char>::name() const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:19: undefined reference to `boost::program_options::arg[abi:cxx11]'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `void command_line::add_arg<unsigned int, true>(boost::program_options::options_description&, command_line::arg_descriptor<unsigned int, true> const&, bool)':
/home/jared/git/src/common/command_line.h:115: undefined reference to `boost::program_options::options_description::find_nothrow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `void command_line::add_arg<bool, false>(boost::program_options::options_description&, command_line::arg_descriptor<bool, false> const&, bool)':
/home/jared/git/src/common/command_line.h:139: undefined reference to `boost::program_options::options_description::find_nothrow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `void command_line::add_arg<unsigned long, false>(boost::program_options::options_description&, command_line::arg_descriptor<unsigned long, false> const&, bool)':
/home/jared/git/src/common/command_line.h:115: undefined reference to `boost::program_options::options_description::find_nothrow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `void command_line::add_arg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false>(boost::program_options::options_description&, command_line::arg_descriptor<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false> const&, bool)':
/home/jared/git/src/common/command_line.h:115: undefined reference to `boost::program_options::options_description::find_nothrow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `void command_line::add_arg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true>(boost::program_options::options_description&, command_line::arg_descriptor<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true> const&, bool)':
/home/jared/git/src/common/command_line.h:115: undefined reference to `boost::program_options::options_description::find_nothrow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, bool) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > boost::program_options::to_internal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)':
/usr/local/include/boost/program_options/detail/convert.hpp:79: undefined reference to `boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/usr/local/include/boost/program_options/detail/parsers.hpp:44: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_prefix()':
/usr/local/include/boost/regex/v4/perl_matcher_common.hpp:339: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long)':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:92: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `void boost::program_options::validate<unsigned long, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long*, long)':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:92: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `main':
/home/jared/git/src/connectivity_tool/conn_tool.cpp:320: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
/home/jared/git/src/connectivity_tool/conn_tool.cpp:323: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::perl_matcher(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >&, boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >)':
/usr/local/include/boost/regex/v4/perl_matcher.hpp:383: undefined reference to `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::construct_init(boost::basic_regex<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, boost::regex_constants::_match_flags)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o: In function `boost::re_detail_106400::perl_matcher<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::match_match()':
/usr/local/include/boost/regex/v4/perl_matcher_non_recursive.hpp:1094: undefined reference to `boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >::maybe_assign(boost::match_results<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<boost::sub_match<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > > const&)'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE[_ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueImcEE[_ZTVN5boost15program_options11typed_valueImcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
CMakeFiles/connectivity_tool.dir/connectivity_tool/conn_tool.cpp.o:(.rodata._ZTVN5boost15program_options11typed_valueIjcEE[_ZTVN5boost15program_options11typed_valueIjcEE]+0x40): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
src/CMakeFiles/connectivity_tool.dir/build.make:107: recipe for target 'src/connectivity_tool' failed
make[2]: *** [src/connectivity_tool] Error 1
CMakeFiles/Makefile2:290: recipe for target 'src/CMakeFiles/connectivity_tool.dir/all' failed
make[1]: *** [src/CMakeFiles/connectivity_tool.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iamsmooth** [comment]
This probably has to do with the boost version on ubuntu 16.04. Until we get that fixed, as a work-around I can tell you that boost 1.60.0 works on ubuntu 16.04 (I just tried it and did a complete build with no errors). So download that version from the boost site, install it to a private directory and use `BOOST_ROOT=location-where-you-installed-boost make`

**Comment by jared03** [comment]
That worked fine to me with boost 1.64.0, Thanks followed this tutorial to install boost 1.64.0
https://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu

**Comment by stoffu** [comment]
I think it's *extremely* difficult, next to impossible, to change the emission rule without contention at this so much later point since the launch. IMO, it is one of the most important social mantra that must be preserved no matter what (except for real existential threat).

Personally, I think the tail emission rate of 0.3 AEON/minute is reasonable, and making it smaller doesn't seem to solve any problem. After all, the goal was to ensure that there will continue to be enough incentive for miners. Why do you think lowering the amount could be better?

> with an emphasis on promoting the usability of those so long decimal places....

I don't understand what you mean by this. Those decimal places will be as useful as they are, regardless of the tail emission rate.

> Keeping into consideration of dynamic block size for which tail emission will play an important role...Why can't we have declining slowly towards 0

The dynamic block size mechanism will stop working if the block reward approaches to zero.

Lastly, Aeon's original social positioning was to be Monero's clone, including the emission schedule. If you want the emission schedule to be changed, you'd better start a new chain, like Wownero did.

**Comment by abhishek1104** [comment]
That's absolutely OK.

I am also not against it completely,just mainly for reconsideration of 0.3 Aeon per minute (or 300 milli aeons per minute with still 8 decimal places) ,that's it.

Or simply why not to reduces those very high Fancy decimal places...And irrespective of it is considered or not it is not a blocker for me ,not to hold/use/trust Aeon (will mainy remain as dissent on this part that's it) ..

**Comment by bitlamas** [comment]
Unless there are some concrete reasons as to why the network would benefit from lowering the tail emission start point, I don't think it's a good idea. In fact, I actually believe there are many (non-technical) benefits on AEON following the same 0.3 coins per minute rate. It puts AEON on par with XMR and that can be good thing.

**Comment by iamsmooth** [comment]
I don't see any consensus in favor of this change nor do I see meaningful discussion of it, so I'm going to close this.
